### ISSUE TITLE
Provide some sort of hint or explanation as to what parameters mean

### ISSUE THREAD

**Issue by Intrepidity** [Incenteev/ParameterHandler#69] opened 2015-01-30 08:39 UTC
It would be nice in my opinion if a parameter in the .dist file is prepended by a comment, that that comment would also be shown when asking for the parameters.

i.e.:
```yml
parameters:
    # A secret key that's used to generate certain security-related tokens
    secret:            test
```

would result in:
```
Some parameters are missing. Please provide them.
A secret key that's used to generate certain security-related tokens: secret (test):
```

It is sometimes hard to convey in a variable name what you want users to input upon install.

**Comment by stof** [comment] 2015-01-30 08:55
The issue is that I cannot access comments. They are ignored by the Yaml parser (which is why they are comments). And implementing my own YAML parser which would include comments in its output (thus being a non-compliant parser) is a no-go.

**Comment by Intrepidity** [comment] 2015-01-30 09:13
Yeah, implementing yaml from scratch is a no-go, i agree. I presume we can't think of another way to add some extra information to a parameter?

If not, you can close this issue and we'll just stick with writing a proper readme.md :P

**Comment by stof** [comment] 2015-01-30 09:14
> I presume we can't think of another way to add some extra information to a parameter?

not if we keep only the .dist file to describe the available params (which is the goal of this library).

**Comment by Intrepidity** [comment] 2015-01-30 09:16
Okidoki, never mind then :) Maybe the yaml parser will gain support at some point to read comments. Until then the work outweighs the possible gain.

**Comment by stof** [comment] 2015-01-30 09:19
Well, this would not make sense. The definition of a comment is precisely that it is ignored by the parser.

Anyway, closing as won't fix

**Closed by stof** 2015-01-30 09:19 UTC

**Comment by Intrepidity** [comment] 2015-01-30 09:25
Not necessarily. Annotations in PHP files are also comments. Yet they're useful extra information. But I get your point.

**Comment by stof** [comment] 2015-01-30 09:33
@Intrepidity technically, docComments are more than comments in PHP (regular comments are also totally ignored)
